# This is a basic workflow to help you get started with Actions

name: A Basic Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build-app: # This workflow contains a single job called "build"
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run a one-line script # Runs a single command using the runners shell
        run: echo Hello, world!
      - name: Run a multi-line script # Runs a set of commands using the runners shell
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-api:
    runs-on: windows-latest
    steps:
      - run: echo "Building API"

  build-db:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello Windows"

  package:
    needs: [build-app, build-db]
    runs-on: macos-latest
    steps:
      - run: echo "Hello MacOS"